### ISSUE TITLE
Spam on building

### ISSUE THREAD

**Issue by leaftail1880** [yracnet/vite-plugin-api-routes#2]
![изображение](https://github.com/yracnet/vite-plugin-api/assets/110915645/b7317fa1-5624-49af-a1b2-abb39d35b3a6)

Since not all endpoinds uses all method, i need to disable this warnings

This can be done by adding this to vite.config.rollupOptions:
```ts
onwarn(warning, handler) {
  if (
    warning.code === "MISSING_EXPORT" &&
    warning.id === "virtual:vite-plugin-api:router"
  )
    return;
  handler(warning);
}
```

This code snipped should be added to tutorial, or as plugin option

**Comment by yracnet** [comment]
Thankyou, I will check it

**Comment by yracnet** [comment]
Applied
