### ISSUE TITLE
request.body passes an empty object

### ISSUE THREAD

**Issue by neondoll** [yracnet/vite-plugin-api-routes#25]
Hello.

I encountered the following problem when using your plugin: request.body contains an empty object, although there is information in the payload.

If you can help me, I will be very grateful, because I have no idea how to get information.

![image](https://github.com/yracnet/vite-plugin-api-routes/assets/48290120/625f1ae1-c228-4572-a430-3cc288648cf3)
![image](https://github.com/yracnet/vite-plugin-api-routes/assets/48290120/3c7b77b2-927f-4ed0-969a-c247899820c7)

Here is my repository: https://github.com/neondoll/neon-anime-list

**Comment by yracnet** [comment]
I will check your repo in this week, thanks for reported

**Comment by yracnet** [comment]
I have see that you use other frameworks, could you share a TAG o BRANCH where this error exist?

**Comment by neondoll** [comment]
I apologize. Since I was looking for solutions and didn't expect to receive an answer, I created a new project, and the previous one was irretrievably lost.

**Comment by yracnet** [comment]
No problem at all! If you need any help with the new project, feel free to reach out. I'm here to help!
