### ISSUE TITLE
Which configuration dirs must be set with root?

### ISSUE THREAD

**Issue by ghost** [yracnet/vite-plugin-api-routes#28]
vite Example:

```js
export default defineConfig({
  root: './src',
  plugins: [
    pluginAPIRoutes({
      cacheDir: '../.api', // this starts without an error
    }),
  ],
  //...
}
```

Call a route errors `Error: Cannot find module 'express' imported from '/home/myproject/.api/configure.js'`
Express is installed.

**Comment by ghost** [comment]
With absolute path it works. `cacheDir: process.cwd() + '/.api',`

**Comment by ghost** [comment]
Na not working. When you use absolute path it will not create .api with configure.ts,....

And the next question, which paths must be set, if you want to use api-Files outside of src?

**Comment by yracnet** [comment]
Do you use a workspace proyect or you need load from external root projrct?
- workspace, it will be works
- external dir project, I need see the vitejs security rules

**Comment by yracnet** [comment]
![image](https://github.com/user-attachments/assets/e99911cd-669c-46ef-a651-74f1fb012b0b)

In my test, I can change the cacheDir to upper directory, I use the relative path, because the plugin use the path.join

![image](https://github.com/user-attachments/assets/6436e613-cddb-47b8-8d65-496da0cfd4d6)

**Comment by yracnet** [comment]
> And the next question, which paths must be set, if you want to use api-Files outside of src?
You need include the {dir, route} in dirs
![image](https://github.com/user-attachments/assets/d0ca1c7f-9b23-4979-8fda-43ac5ce06e3b)
