### ISSUE TITLE
Does not parse JSON by default

### ISSUE THREAD

**Issue by PlayWolfYT** [yracnet/vite-plugin-api-routes#7]
I think it would make sense to automatically parse JSON with the express json parser, otherwise people might get confused why their Request-Bodies are empty.

Looking at the code, I think the idea was that it is supposed to do that, though I found out that it does not.

Making the following changes to the `src/plugin/write/handlerFile.ts` would fix this:
```ts
//...
export const handler = express();

// Add JSON-Parsing
handler.use(express.json());
handler.use(express.urlencoded({ extended: true }));

//...
```

**Comment by yracnet** [comment]
It was applied in 1.0.2.
